/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "Vlpp.h"

#include "..\..\Source\Console.Windows.cpp"
#include "..\..\Source\Primitives\DateTime.Windows.cpp"
#include "..\..\Source\Strings\Conversion.Windows.cpp"
#include "..\..\Source\UnitTest\UnitTest.Windows.cpp"
