/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "Vlpp.h"

#include "..\..\Source\Console.Linux.cpp"
#include "..\..\Source\Primitives\DateTime.Linux.cpp"
#include "..\..\Source\Strings\Conversion.Linux.cpp"
#include "..\..\Source\UnitTest\UnitTest.Linux.cpp"
