/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "Vlpp.h"

#include "..\..\Source\Basic.cpp"
#include "..\..\Source\Console.cpp"
#include "..\..\Source\Exception.cpp"
#include "..\..\Source\GlobalStorage.cpp"
#include "..\..\Source\String.cpp"
#include "..\..\Source\Collections\PartialOrdering.cpp"
#include "..\..\Source\UnitTest\UnitTest.cpp"
